# Generated by Django 4.2.2 on 2023-07-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='tile1',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='services',
            name='title2',
            field=models.CharField(max_length=264),
        ),
    ]
