# Generated by Django 4.2.2 on 2023-07-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_tile1_alter_services_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
