# Generated by Django 4.2.2 on 2023-07-02 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_services_created_services_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-created'], 'verbose_name': 'services', 'verbose_name_plural': 'Services'},
        ),
    ]
